Parametrise configurations
distributed-technologies/mukube-configurator pull request #14
Opened 2021-04-22 13:18 UTC by skovbakke

Added parameters to the Makefile allowing config and requirement files to be specified on the command-line. This is usefull when environment variables are stored in a separate location. 

Also did some small renaming & refactoring. There was an issue where the config script would fail when the number of workers was zero and the `build/cluster/worker` directory did not exist.

2021-04-26 11:47 UTC, jacobcrawford requested changes
Should the image_requirements and helm_requirements files not be referenced by the environment variables?
Otherwise looks good.

2021-04-26 11:47 UTC, jacobcrawford commented on scripts/pack_helm_charts.sh
> +cat helm_requirements | grep -w ".*http.*"   | while read p; do
Should this file not be referenced by the HELM_REQUIREMENTS variable?

2021-04-26 11:47 UTC, jacobcrawford commented on scripts/pack_helm_charts.sh
> +linesInFile=$(grep -w ".*http.*" -c helm_requirements)
same

2021-04-28 10:14 UTC, skovbakke commented on scripts/pack_helm_charts.sh
> +linesInFile=$(grep -w ".*http.*" -c helm_requirements)
yes

2021-04-28 10:14 UTC, skovbakke commented on scripts/pack_helm_charts.sh
> +cat helm_requirements | grep -w ".*http.*"   | while read p; do
yes

2021-04-28 11:00 UTC, jacobcrawford approved these changes
looks good.

2021-04-28 11:00 UTC, merged