Prepare flush etcd service
distributed-technologies/mukube-configurator pull request #20
Opened 2021-05-19 14:00 UTC by skovbakke

Refactored parts of the boot script making it easier to add functionality. Then added functionality needed for the flush-etcd-service.

2021-05-19 15:28 UTC, skovbakke commented
Did some additional bugfixing. Everything should be working again.

2021-05-20 11:59 UTC, jacobcrawford requested changes
Looks good, but the readme and docs should be updated to reflect the changes.

2021-05-20 13:32 UTC, jacobcrawford requested changes

2021-05-20 13:32 UTC, jacobcrawford commented on scripts/prepare_k8s_configs.sh
> +	worker)
Remove unused variable.

2021-05-20 13:44 UTC, jacobcrawford approved these changes
looks good.

2021-05-20 13:47 UTC, merged