Support specifying load balancer ip range and ingress lb ip
distributed-technologies/mukube-configurator pull request #35
Opened 2021-11-05 09:08 UTC by klausenbusk

It is part of the network configuration so should be handled here.

---

It has been cleared with @jakobhviid.

2021-11-08 13:45 UTC, klausenbusk commented
I have tested the `helm install` command and the values seem to be passed correctly.

2021-11-08 14:50 UTC, skovbakke requested changes

2021-11-08 14:50 UTC, skovbakke commented on templates/boot.sh
> +              $release $FILE
I see that this works. However, currently the script was made to support installing any helm chart, and parts of the script were made to support this.  
If we decide to use these cmd-line options (which set values specific to yggdrasil) we might as well move the helm chart value into the config file as well. The makefile will be simpler then. @jacobcrawford what do you think?

2021-11-08 14:56 UTC, klausenbusk commented on templates/boot.sh
> +              $release $FILE
https://github.com/distributed-technologies/mukube-configurator/pull/33 is a more generic approach, but IMO it make sense to be explicit about some of the options (lb, proxies etc.).

2021-11-08 15:04 UTC, jacobcrawford commented on templates/boot.sh
> +              $release $FILE
I dont think i see why we need to handle this configuration here and not in yggdrasil?

2021-11-09 11:10 UTC, skovbakke approved these changes
LGTM. I have created a task to refactor the configurator based on the talk we had today

2021-11-09 11:10 UTC, merged