Feature/proxy
distributed-technologies/mukube-configurator pull request #36
Opened 2021-11-09 14:18 UTC by klausenbusk

2021-11-10 18:15 UTC, jacobcrawford requested changes
Action needed for backward compatibility.

2021-11-10 18:15 UTC, jacobcrawford commented on templates/boot.sh
> +              --set lb-proxy.enabled=true \
I dont think we should enable the lb-proxy always. To be backwards compatible while in transition to the sync service setup, we should be able to disable these features if left out of the mukube-configurator configuration.

2021-11-10 18:16 UTC, jacobcrawford commented on docs/config.md
> +### HTTP_PROXY_SERVER
We should be able to disable the use of a proxy to be backward compatible right? Default should be disabled.

2021-11-11 10:07 UTC, klausenbusk commented on templates/boot.sh
> +              --set lb-proxy.enabled=true \
I agree, this was only posted to get some early feedback. The HTTP proxy feature is opt-in now.

2021-11-11 10:07 UTC, klausenbusk commented on docs/config.md
> +### HTTP_PROXY_SERVER
See https://github.com/distributed-technologies/mukube-configurator/pull/36#discussion_r747366709

2021-11-12 07:37 UTC, jacobcrawford requested changes
I think we need to document how to inject a "values" file for a helm chart. Otherwise, it looks good.

2021-11-12 08:23 UTC, jacobcrawford approved these changes
LGTM

2021-11-12 08:38 UTC, merged