docs: Configurations are placed in config dir
distributed-technologies/mukube-configurator pull request #48
Opened 2022-02-14 10:53 UTC by skovbakke

Clarify in the README.md that the configuration files should be placed in a directory named `config`.

2022-02-15 06:33 UTC, jacobcrawford requested changes

2022-02-15 06:33 UTC, jacobcrawford commented on README.md
> +The entry point for the project is the `Makefile` in the root folder, which reads the `config` file, located in the `config` directory, for a full cluster setup.
The `config/config` structure has always been a source of confusion. Should we not change the folder name to "input", as everything in this folder is input for the script?

2022-02-16 11:13 UTC, MadsHT reviewed
A few comments

2022-02-16 11:13 UTC, MadsHT commented on README.md
> +The entry point for the project is the `Makefile` in the root folder, which reads the `config` file, located in the `config` directory, for a full cluster setup.
I agree, We should either rename the config file og provide a path example:

```suggestion
The entry point for the project is the `Makefile` in the root folder, which reads the `config` file, located in the `config` directory, for a full cluster setup.

Files required in the config folder
`mukube-configurator/config/config`
`mukube-configurator/config/helm_requirements`
`mukube-configurator/config/values/*.yaml`

```

2022-02-16 11:13 UTC, MadsHT commented on README.md
> +### [config/config](docs/config.md)
Maybe move this to the top, since the first part of this doc is about the config file?

2022-02-17 14:06 UTC, skovbakke commented on README.md
> +The entry point for the project is the `Makefile` in the root folder, which reads the `config` file, located in the `config` directory, for a full cluster setup.
I have renamed the folder to input as requested

2022-02-17 14:08 UTC, skovbakke commented on README.md
> +### [config/config](docs/config.md)
I am not sure I understand what you are requesting. What should be moved?

2022-02-17 15:21 UTC, skovbakke commented
I have renamed the config folder to input. Hopefully everything is more clear now 😀

2022-02-18 06:51 UTC, jacobcrawford approved these changes
LGTM 😸

2022-02-21 10:41 UTC, skovbakke commented
Mads, do you want to look at this again?

2022-02-21 10:44 UTC, MadsHT approved these changes
LGTM, It's less confusing with `input` as folder name

2022-02-21 15:02 UTC, merged