Azure VM report ready and network configuration
distributed-technologies/mukube-configurator pull request #58
Opened 2022-12-01 17:39 UTC by dstoft

2022-12-07 12:47 UTC, klausenbusk commented on scripts/prepare_cluster.sh
> +then
Same:
```suggestion
if [ $IS_IN_AZURE == "true" ]; then
```

2022-12-07 12:47 UTC, klausenbusk commented on scripts/prepare_cluster.sh
> +    then
Same:
```suggestion
    if [ $IS_IN_AZURE == "true" ]; then
```

2022-12-07 12:47 UTC, klausenbusk commented on scripts/prepare_master_HA.sh
> +fi
Perhaps?
```suggestion
export KEEPALIVED_INTERFACE=$NODE_NETWORK_INTERFACE
if [ $IS_IN_AZURE == "true" ]; then
    export KEEPALIVED_INTERFACE=vxlan0
fi
```

2022-12-07 12:47 UTC, klausenbusk commented on templates/10-systemd-network.network
> +DHCP=${USE_DHCP}
So we have both a static IP and DHCP in Azure? Looks a bit odd :)

2022-12-07 12:47 UTC, klausenbusk commented on templates/azure-health.sh
> +do
```suggestion
until [ "$attempts" -gt 2 ]; do
```

2022-12-07 12:47 UTC, klausenbusk commented on templates/azure-health.sh
> +    then
```suggestion
    if [ $? -eq 0 ]; then
```

Again perhaps we could use the nicer `(())` syntax? What u think?

2022-12-07 12:47 UTC, klausenbusk commented on templates/azure-health.sh
> +then
```suggestion
if [ "$retrieved_goal_state" != "true" ]; then
```

2022-12-07 12:47 UTC, klausenbusk commented on templates/azure-health.sh
> +do
Same:
```suggestion
until [ "$attempts" -gt 1 ]; do
```

I guess we could also use this syntax (perhaps a bit easier to understand):
```suggestion
until (($attempts > 1)); do
```

2022-12-07 12:47 UTC, klausenbusk commented on templates/azure-health.sh
> +    then
```suggestion
    if [ $? -eq 0 ]; then
```
Again perhaps we could use the nicer `(())` syntax? What u think?

2022-12-07 12:47 UTC, klausenbusk commented on templates/boot.sh
> +        then
```suggestion
        if [ $IS_IN_AZURE == "true" ]; then
```

2022-12-07 12:47 UTC, klausenbusk commented on templates/keepalived.conf
> +    interface ${KEEPALIVED_INTERFACE}
This breaks the `en*` expanding: https://github.com/distributed-technologies/mukube-configurator/blob/main/templates/boot.sh#L29.

Implemented in this commit: https://github.com/distributed-technologies/mukube-configurator/commit/f34dc79a0dc4558593cbe1a55014e08f606705ef.

2022-12-08 06:59 UTC, jacobcrawford commented on scripts/prepare_systemd_network.sh
> +    echo "
Instead of having a file template inline, we should extract this to a file like the other templates. This way is more futureproof when we port to another non-horrible implementation language😄

2022-12-08 07:02 UTC, jacobcrawford commented on templates/azure-health.sh
> +Host: 168.63.129.16\r
When we hardcode I think an explanation is needed of why this is needed.

2022-12-08 07:06 UTC, jacobcrawford commented on templates/azure-health.sh
> +# Based on https://learn.microsoft.com/en-us/azure/virtual-machines/linux/no-agent#add-required-code-to-the-vm
Also, add a comment as to what this file does on a high level.

2022-12-08 07:07 UTC, jacobcrawford requested changes
Overall great work, I just has a few comments 😄

2022-12-08 07:42 UTC, dstoft commented on templates/10-systemd-network.network
> +DHCP=${USE_DHCP}
My lack of knowledge regarding network and its configuration is now on public display. Can everything under [network], except DHCP, be removed when DHCP is in use? And what is the pretty way to do this in bash?

2022-12-08 13:42 UTC, klausenbusk commented on scripts/prepare_cluster.sh
> +        fi
I think we should just add the default value at line 66, ex:
```
AZURE_VXLAN_IPRANGE=${AZURE_VXLAN_IPRANGE:-10.0.98.0/24}
```
and then simplify this to:

```suggestion
        newrange=${AZURE_VXLAN_IPRANGE%.*}.$unique_fourth_octet/${AZURE_VXLAN_IPRANGE#*/}
        export VXLAN_IP=$newrange
```

2022-12-08 13:42 UTC, klausenbusk commented on docs/config.md
> +### AZURE_VXLAN_IPRANGE
Please add both options to the list at the top of this file :)

2022-12-08 13:42 UTC, klausenbusk commented on docs/config.md
> +(Optional) If the "IS_IN_AZURE" is set to "true", this value can be used to set the range in which the VXLAN IP will be from. The last octet of the IP range will be replace with the last octet of the
The default value should be documented:
```suggestion
(Optional) If the "IS_IN_AZURE" is set to "true", this value can be used to set the range in which the VXLAN IP will be from. The last octet of the IP range will be replace with the last octet of the NODE_HOST_IP, such that it is unique for all nodes. (default: `10.0.98.0/24`).
```

2022-12-08 13:42 UTC, klausenbusk commented on scripts/prepare_systemd_network.sh
> +
I guess it would make sense to move these into the `if` scope.

2022-12-08 13:45 UTC, klausenbusk commented on scripts/prepare_systemd_network.sh
> +" >> $OUTPUT_DIR/foo.network
Let's also rename this file to `vxlan0` :)
```suggestion
" > $OUTPUT_DIR/vxlan0.network

    for ((i=0; i<${#MASTERS[@]}; i++)); do
        if [ ${MASTERS[i]} = $NODE_HOST_IP ]; then
            continue
        fi

        echo "
[BridgeFDB]
MACAddress=00:00:00:00:00:00
Destination=${MASTERS[i]}
" >> $OUTPUT_DIR/vxlan0.network
```

2022-12-08 13:48 UTC, klausenbusk commented on templates/10-systemd-network.network
> +DHCP=${USE_DHCP}
Have you tried just removing the `DHCP` option from the `.network` file? Doing some quick testing in your test VM, it seems to be working.

2022-12-09 10:38 UTC, dstoft commented on docs/config.md
> +### AZURE_VXLAN_IPS
Change it to a range, and then explained a bit more regarding why we are using a VXLAN.

2022-12-13 10:07 UTC, jacobcrawford commented on scripts/prepare_systemd_network.sh
> +    echo "
Yes the first one can easily be extracted. 

For the second one, i used to export variables that needed to be substituted and then simple catting the file will substitute the variables if they are defined with "${VAR}":

E.g. the check_apiserver.sh script template:
![image](https://user-images.githubusercontent.com/22328547/207288458-08a176f3-af98-4640-a3cd-305230c2b10b.png)
Has the APISERVER_DEST_PORT variable defined which can be defined and substituted:
![image](https://user-images.githubusercontent.com/22328547/207288710-9348e4fb-ef76-4b15-ae66-e805fac1ce95.png)

Does it make sense?

2022-12-14 09:27 UTC, dstoft commented on scripts/prepare_systemd_network.sh
> +    echo "
After talking with Jacob, we agreed that there are no smart way to rewrite the for-loop (that writes "BridgeFDB" entries) to a template file, therefore this conversation is resolved.

2022-12-14 12:21 UTC, klausenbusk commented on scripts/prepare_cluster.sh
> +fi
`if` condition isn't needed.
```suggestion
AZURE_VXLAN_IPRANGE=${AZURE_VXLAN_IPRANGE:-10.0.98.0/24}
```

2022-12-14 12:21 UTC, klausenbusk commented on templates/azure-health.sh
> +until (("$attempts" > 5)); do
Neither quotation nor `$` is required.
```suggestion
until ((attempts > 5)); do
```

2022-12-14 12:21 UTC, klausenbusk commented on templates/azure-health.sh
> +until (($attempts > 5)); do
Same
```suggestion
until ((attempts > 5)); do
```

2022-12-14 12:21 UTC, klausenbusk commented on scripts/prepare_cluster.sh
> +        unique_fourth_octet=$(echo $NODE_HOST_IP | cut -d . -f 4)
Let's try to be consistent :)
```suggestion
        unique_fourth_octet=$(cut -d . -f 4 <<< "$NODE_HOST_IP")
```

2022-12-21 10:23 UTC, MadsHT requested changes
Few cosmetic things 👍

2022-12-21 10:23 UTC, MadsHT commented on docs/config.md
> +(Optional) If the "IS_IN_AZURE" is set to "true", this value can be used to set the range in which the VXLAN IP will be from. The last octet of the IP range will be replace with the last octet of the
Is this not required when `IS_IN_AZURE` is true? 
And what does this do if `IS_IN_AZURE` is false and I set this anyway?

2022-12-21 10:23 UTC, MadsHT commented on scripts/prepare_systemd_network.sh
> +# If in running in Azure, then create the two network files ".netdev" and ".network" required by the new VXLAN
```suggestion
# If running in Azure, then create the two network files ".netdev" and ".network" required by the new VXLAN
```

2022-12-21 10:23 UTC, MadsHT commented on scripts/prepare_systemd_network.sh
> +source $VARIABLES
Should'nt there be a check if this exists?

2022-12-21 10:23 UTC, MadsHT commented on scripts/prepare_systemd_network.sh
> +    done
Indentation of the for loop

```suggestion
  for ((i=0; i<${#MASTERS[@]}; i++)); do
      if [ ${MASTERS[i]} = $NODE_HOST_IP ]; then
          continue
      fi

      echo "
[BridgeFDB]
MACAddress=00:00:00:00:00:00
Destination=${MASTERS[i]}
" >> $OUTPUT_DIR/vxlan0.network
  done
```

2022-12-21 10:24 UTC, MadsHT commented
Also I am a little confused about the `templates/azure-health.sh` and `templates/boot.sh` why are they located in templates? o.O

2022-12-21 10:38 UTC, jacobcrawford requested changes
A few comments 😸

2022-12-21 10:38 UTC, jacobcrawford commented on scripts/prepare_cluster.sh
> +        # Retrieve the last octet of the IP of the current node
I think the comments along the way is good, but we might need a high-level explanation of what this part does and why.

2022-12-21 10:38 UTC, jacobcrawford commented on templates/boot.sh
> +            /bin/bash /azure-health.sh
In this context, the filename does not make sense. It should somewhat reflect that we are reporting to Azure that the VM is OK

2022-12-21 10:38 UTC, jacobcrawford commented on templates/boot.sh
> +        # If in Azure, then replace the "NODE_NETWORK_INTERFACE" variable in "keepalived.conf" with "vxlan0", else replace it with the network interfaces provided by the config
Why do we do this in the boot script and not while building the templates?

2022-12-21 10:38 UTC, jacobcrawford commented on templates/boot.sh
> +        if [ $IS_IN_AZURE == "true" ]; then
Same as above

2022-12-21 13:08 UTC, dstoft commented on scripts/prepare_systemd_network.sh
> +source $VARIABLES
There are no checks in any of the other files regarding this, so I'm assuming no.

2022-12-22 08:50 UTC, dstoft commented on templates/boot.sh
> +        # If in Azure, then replace the "NODE_NETWORK_INTERFACE" variable in "keepalived.conf" with "vxlan0", else replace it with the network interfaces provided by the config
I tried to change this as well, however, it was rejected by Kristian:
https://github.com/distributed-technologies/mukube-configurator/pull/58#discussion_r1042162092

2022-12-22 08:50 UTC, dstoft commented on templates/boot.sh
> +        if [ $IS_IN_AZURE == "true" ]; then
See above answer.

2022-12-22 09:09 UTC, dstoft commented on scripts/prepare_cluster.sh
> +        # Retrieve the last octet of the IP of the current node
I have added "Every node's VXLAN needs a unique IP range where the VIP of the k8s control plane is accessible.", as I know the VIP has to be in the range of all of these unique ranges. If you want more high level explanations, then we will have to wait for @klausenbusk to come back from holiday.

2022-12-22 09:10 UTC, dstoft commented
> Also I am a little confused about the `templates/azure-health.sh` and `templates/boot.sh` why are they located in templates? o.O

As far as I understand, it is because the "scripts" folders are executed by Mukube itself, and the "templates" folder is executed on each node itself when the node is booting. Both of the files mentioned are executed on each node when they are booting.

2022-12-22 09:36 UTC, MadsHT approved these changes
LGTM 🎉

2022-12-30 08:06 UTC, jacobcrawford approved these changes
LGTM (sort of)

2023-01-02 07:32 UTC, merged